import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// Shared sidebar definition used by every product docs instance. Each product's
// sidebar is autogenerated from its own docs/ folder, so a product controls its
// navigation purely by how it arranges files (and optional _category_.json
// files) next to its code. The sidebar id is "product" — referenced by the
// navbar items generated in docusaurus.config.ts.
const sidebars: SidebarsConfig = {
  product: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
