import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// Sidebar for the hub's own platform-level docs (docs-hub/). Autogenerated from
// the folder structure so authors just drop in Markdown files.
const sidebars: SidebarsConfig = {
  docs: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
